---
title: "ExtraDE_Plots_Volcano"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("BiocManager")
#BiocManager::install("Seurat")
#BiocManager::install("ggplot2")
#BiocManager::install("sctransform")

library(Seurat)
library(ggplot2)
library(dplyr)
library(ape)
library(cowplot)
library(Matrix)
library(EnhancedVolcano)
library(knitr)
library(readr)

#find out where you are
getwd()

#Specify where your files are
dir= "/Users/whippoorwill/Desktop/Sequencing/Paz_Thalamus_2022/"
datafolder = "Data/Seurat"
filename = "Microglia_Paz_MG_Thal_filtered.RData"
organism = "Mouse"
defile = "mg1_named_markers.csv"

m = c("nCount_RNA","nFeature_RNA","percent.mito","percent.ribo")
Plotfolder = "Plots"

if(organism == "Mouse"){library(org.Mm.eg.db)}
if(organism == "Human"){library(org.Hs.eg.db)}
if(organism == "Zebrafish"){library(org.Dr.eg.db)}
```
Load in your filtered dataset
```{r}
load(file.path(dir,datafolder,filename))
```


*Volcano Plot*
```{r}
de = read.csv(file = file.path(dir,"Spreadsheets",defile),stringsAsFactors = F)
head(de)
```

Set your parameters
```{r}
#Minimum fold change (i.e. 1.15 = 15% increase)
minfc = 1.3
#Max adj. p value
alpha = 1e-25
#Clusters selected
categories = levels(as.factor(de$cluster))
#Genes to highlight
ngenes = 20
```


```{r}

colnames(de)[8] = "Gene"
newlist = list()
clusters = levels(as.factor(de$cluster))

#Split by cluster
i = 1
for (cluster in clusters){
  newlist[[cluster]] = de[de$cluster == cluster,]
  i = i+1
}

#select a single cluster

for (category in categories){
  fc = newlist[[category]]
  fc = fc[!is.na(fc$avg_log2FC),]
  colorkeysdown = fc$Gene[fc$avg_log2FC < -log2(minfc) & fc$p_val_adj < alpha]
  colorkeysup = fc$Gene[fc$avg_log2FC > log2(minfc) & fc$p_val_adj < alpha]

#Either highlight specific genes or pick the top genes in colorkeysup/down
  top = fc[fc$p_val_adj<alpha,]
  top = top[order(top$avg_log2FC),"Gene"]
  highlight = c(head(top,ngenes),tail(top,ngenes))
  
  #Either highlight specific genes or pick the top genes in colorkeysup/down
  if (category == "Dam2"){highlight = c(head(top,ngenes),dam2genes[81:100])
  }

  allcolors = rep("darkgrey",length(fc$Gene))
  names(allcolors) = fc$Gene

  allcolors[names(allcolors) %in% colorkeysdown] = "blue"
  allcolors[names(allcolors) %in% colorkeysup]= "red"
  allcolors[names(allcolors) %in% highlight]= "yellow"

  names(allcolors)[allcolors == "yellow"] = "labelled"
  names(allcolors)[allcolors == "red"] = "u"
  names(allcolors)[allcolors == "darkgrey"] = "-"
  names(allcolors)[allcolors == "blue"] = "d"
  
  setEPS()
  postscript(file.path(dir,"Plots",paste0("Volcano_",category,".eps")))
  print(EnhancedVolcano(fc,
                lab = fc$Gene,
                x = 'avg_log2FC',
                y = 'p_val_adj',
                xlim = c(-6,6),
                title = category,
                subtitle = "",
                drawConnectors = F,
                legendPosition = 'right',
                pCutoff = alpha,
                FCcutoff = log2(minfc),
                selectLab = highlight,
                col=c('black', 'black', 'black', 'red3'),
                colCustom = allcolors,
                gridlines.major = F,
                gridlines.minor = F,
                colAlpha = 1))
  dev.off()

  print(EnhancedVolcano(fc,
                lab = fc$Gene,
                x = 'avg_log2FC',
                y = 'p_val_adj',
                xlim = c(-6,6),
                title = category,
                subtitle = "",
                drawConnectors = F,
                legendPosition = 'right',
                pCutoff = alpha,
                FCcutoff = log2(minfc),
                selectLab = highlight,
                col=c('black', 'black', 'black', 'red3'),
                colCustom = allcolors,
                gridlines.major = F,
                gridlines.minor = F,
                colAlpha = 1))
}
```

